datasources:
  default:
    url: "jdbc:sqlite:skillmatch.db"
    driverClassName: "org.sqlite.JDBC"
    maximum-pool-size: 1
    minimum-idle: 1
    connection-test-query: "SELECT 1"
    read-only: false
    auto-commit: true
    
micronaut:
  data:
    schema-generate: CREATE_DROP
    pageable:
      default-page-size: 20
  transaction:
    enabled: true
